### ISSUE TITLE
Make sure GUI only lists "en"

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCATForPython#2]
Currently there is only one language supported. The GUI should only list that one.

Ideally, it should look in a Languages subdir.

**Comment by ways2read** [comment]
The GUI code submitted only lists `en` for Languages. When the folder structure is decided and implemented this can be walked to build up the options for the drop-down list.

**Comment by NSoiffer** [comment]
Folder structured is now implemented.

**Comment by NSoiffer** [comment]
@ways2read: This is done and can be closed, right?

**Comment by ways2read** [comment]
Yes, looks like this is working as expected.
