### ISSUE TITLE
Dialog does not display correctly at lower resolutions

### ISSUE THREAD

**Issue by ways2read** [NSoiffer/MathCATForPython#24]
The wxForms library should set the dialog according to the resolution and the controls in the form. However, the window is too small on lower resolutions leading to the right-hand side and the lower part of the dialog not being visible.

It is possible that absolute values were used for the window when experimenting in the early days of learning the layout tool.

**Comment by NSoiffer** [comment]
@ways2read : Is this fixed? If so, please close the issue.

**Comment by ways2read** [comment]
Confirmed fixed
