### ISSUE TITLE
Upper and lowercase roman letters are not distinguished

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCATForPython#29]
I was relying on NVDA to distinguish between them based on its preference settings. But that isn't happening. Perhaps MathCAT is calling a lower level speech function so NVDA doesn't get a chance to apply its settings.

**Comment by jasonjgw** [comment]
Interestingly, in my testing, NVDA did say "cap" before uppercase Greek letters. As @NSoiffer notes, however, capital Roman letters are not distinguished at all in the spoken output. (The braille is of course correct.)

The result is the same regardless of the user's NVDA speech settings for treatment of uppercase letters.

**Comment by jasonjgw** [comment]
Now fixed - thank you, @nsoiffer.
