### ISSUE TITLE
Do not line break for a new Math block when screen layout is on

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCATForPython#49]
It seems like each Math block gets its own line - or at least that is how NVDA seems to be rendering it to me - even though I suspect that visually, sighted students see them as one flowing paragraph. While it can often be useful to have the Math content spread out across a few lines for sake of digestability, but when each Math block is just a1, a2 a3, or another relatively trivial expressions, it seems counter-productive to have to arrow so much to re-read that text. I envision this to behave like links when screen layout is toggled; when screen layout is off, all Math blocks get their own line and when it is on, multiple Math blocks may be rendered on the same line as they appear visually.

**Comment by NSoiffer** [comment]
The problem seems to have gone away with this preliminary build of [MathCAT 0.3.0](https://drive.google.com/file/d/1enIAzcc6Qa1J7ZPmAG0QNRBeWY4GLdIl/view?usp=sharing). Please let me know if that is the case for you.

**Comment by bhavyashah** [comment]
Yes, I am no longer facing this issue in the new build - thanks for pointing this out!

**Comment by NSoiffer** [comment]
I tried a few other pages and they were hit or miss -- sometimes it stopped at inline equations and sometimes not. For bigger equations, it was more likely to stop. This might have something to do NVDA's preference "Maximum number of characters on one line" (under "Browse Mode" in settings panel). With math, there is a lot of SSML generated around some characters and _maybe_ NVDA is counting all of the markup.

If you run into the problem, it would be really helpful if you played with this option to see if it effects the stopping. If so, let me know and I'll dig into the NVDA and see if I can figure out whether a bug report needs to be filed. Thanks.

**Comment by bhavyashah** [comment]
The issue persists with consistency. I maxed out the "Maximum Number of Characters on One Line" that is 250, and that did not help with any of my Math blocks and the line break before and after each (including short expressions like $X=1$). If I configure that option to something low like 10, long words like "probability" get split across lines but somewhat long Math expressions like $P(X=k)=q^{k-1} p$ stay intact and occupy their own line as usual.
