### ISSUE TITLE
Using the "Reset to defaults" button in the MathCAT Preferences dialog changes Language to Ελληνικά (el)

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCATForPython#59]
## Issue: 

Using MathCAT 0.3.7, clicking the "Reset to defaults" button in the MathCAT Preferences dialog changed the language to Ελληνικά (el) from the previous setting of English (en). 

![image](https://github.com/NSoiffer/MathCATForPython/assets/117550/eafde408-bff0-462a-bc79-51b415aa46af)

## Desired Effect:

Probably best to switch to the NVDA Language or just leave it alone?

**Comment by NSoiffer** [comment]
You must have grabbed the Greek build. It doesn't happen in the current build. 

In the current build I added a "Use current voice (Auto)" for the language. That is now the default and it goes back to that.
