### ISSUE TITLE
Provide GUI option for disabling auto-zoom

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCATForPython#61]
Personally, I've never been able to appreciate auto-zoom in Math Player or in MathCAT. Rather than easing my navigation, it feels jumpy and disorienting to me when exploring a Math expression. That remark aside, a few requests below:
1 Document how to disable auto-zoom by editing one of the MathCAT settings files manually
2 Provide a GUI option to toggle auto-zoom
3 Change the default to having auto-zoom disabled rather than enabled

(2) obviates (1) in my view and I don't feel strongly about (3). Hence, as the issue title suggests, my main request is (2).

**Comment by NSoiffer** [comment]
I'm not sure what you mean by auto-zoom. What I call auto zoom is the automatic zooming out when you cross a structure boundary such as exiting the numerator or denominator when moving right. If that is what you mean, there is a GUI option to control that in the Navigation pane of the MathCAT settings dialog ("Automatic zoom out of 2D structures").

I've heard from several users is that they think this is good feature. Power users who listen at very high rates and "bang" on the arrow keys say they want walls, so they don't like it. However, power users are AFAIK, a much smaller percentage of users, so having it on as a default I think is appropriate.

If you mean something else by "auto-zoom", please describe the behavior you don't like.

**Comment by bhavyashah** [comment]
Oops, that was a slipup on my part. I entirely forgot about the MathCAT's navigation options where as you said, that option is already present. Also, please ignore my thoughts on the default for now. I put some more thought into what my ideal behaviour would look like (and realized why that might be tricky to implement), and will also have updated thoughts once I actually try reading Math with autozoomout disabled. Closing for now.
