### ISSUE TITLE
Add "copy as" to the dialog

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCATForPython#67]
Add a "CopyAs" preference with values "MathML" (default), "LaTeX", and "ASCIIMath" (when https://github.com/NSoiffer/MathCAT/issues/255 is completed).

These would use the braille codes since they are ASCII, not dots.

**Comment by ways2read** [comment]
On which panel of the preferences dialogue should this setting be?

**Comment by NSoiffer** [comment]
Odd, I thought I had commented on this already.

This may need to be a new panel. However, this feature only works when the expression is in focus, which means it is active during navigation. So maybe it can go there. There aren't many things in that panel.

**Comment by ways2read** [comment]
Checking the UI design:
<img width="427" alt="image" src="https://github.com/NSoiffer/MathCATForPython/assets/9092859/b2239ad5-c2e5-4762-aef9-3726403a4716">

**Comment by NSoiffer** [comment]
Looks good. I like that you added a gap for the "copy..." as it is a bit different than the others and so it is good to separate it a little.

**Comment by NSoiffer** [comment]
Completed.
