### ISSUE TITLE
Translation system error

### ISSUE THREAD

**Issue by seanbudd** [NSoiffer/MathCATForPython#72]
There is an error preventing translations of MathCAT

```
Failure during addon translation update: MathCAT
+ addonPath=/home/nvdal10n/mr/addons/MathCAT
+ cd /home/nvdal10n/mr/addons/MathCAT
+ '[' 0 -ne 0 ']'
+ mr addon2svn
mr addon2svn: /home/nvdal10n/mr/addons/MathCAT
Running addon2svn for MathCAT
Already on 'stable'
Your branch is up to date with 'origin/stable'.
HEAD is now at 70f2575 Merge branch 'stable' of https://github.com/nvdaaddons/mathCATForPython into stable
scons: Reading SConscript files ...
ModuleNotFoundError: No module named 'markdown':
  File "/home/nvdal10n/mr/addons/MathCAT/sconstruct", line 12:
    import markdown
mr addon2svn: command failed
```

**Comment by NSoiffer** [comment]
It builds ok on github and my desktop computer. The github action has:
```
        pip install scons markdown
        sudo apt update
        sudo apt install gettext
```

Looking further, this seems to be happening because `sconstruct` has
```
import markdown
```
This was moved by someone other than me from inside `def md2html` to the top level to make the linter happy. The original usage came code that I got from somewhere else (probably from @nvdaes). 

Is importing `markdown` in option in the main build? Should I see what happens if I remove it or move it back to `md2html`?

**Comment by nvdaes** [comment]
@NSoiffer , I don't have issues in my add-ons with scons, so I don't know.
You may look at:

https://github.com/nvdaes/clipContentsDesigner

Or any other add-on from my GitHub account.

**Comment by NSoiffer** [comment]
Your clipContentsDesigner link has
```
uses: nvdaes/nvdaAddonWorkflows/.github/workflows/automaticRelease.yaml@main
```
and that uses `pip install Markdown`. There is a difference in case. I don't know if that matters.

@seanbudd: It seems that including that install is what is needed. I don't think this is a MathCAT issue.

**Comment by NSoiffer** [comment]
There have been some updates since this and (I think) they were ok except for a bogus security warning.

Can I close this?

**Comment by seanbudd** [comment]
@nvdaes - is this still failing in the translation system?

**Comment by nvdaes** [comment]
@seanbudd  and @NSoiffer , I've just run mr addon2svn for MathCAT from the server manually, and all is OK. I think that this issue can be closed.

**Comment by nvdaes** [comment]
@NSoiffer , you invited me to this repo as a collaborator. I'll close this now so you don't need to do it.
