### ISSUE TITLE
NVDA Addon Store "stable version" link does not provide latest version listed in 

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCATForPython#76]
On the NVDA addons web page for MathCAT, the MathCAT Update Log lists 0.6.3 however the stable version link provides version 0.5.6. We expected to get 0.6.3 when we downloaded.

![image](https://github.com/user-attachments/assets/edf3ccaf-c3a9-4d09-b01e-7f69bbc8369c)

**Comment by NSoiffer** [comment]
There was some (bogus) security issue that an automatic checker flagged (one out of ~25 checkers flagged some python library I used as having a problem -- it was obviously a false negative and I wrote to both the company and discussed it in an issue). I thought I got them to agree to override that, but apparently it didn't happen. I'm about to release a new build, so I'm closing this issue and hopefully the new build won't have the problem.
