### ISSUE TITLE
MathCAT crashes with this math in Word

### ISSUE THREAD

**Issue by GeorgeKerscher** [NSoiffer/MathCATForPython#77]
while doing the homework for the Math-A11Y  DAISY project with the reading and Writing of Math, Somehow I managed to crash MathCAT. I copied the NVDA log entry  and pasted it under the expression.

It is problem 5.
[Math Homework by George.docx](https://github.com/user-attachments/files/16489018/Math.Homework.by.George.docx)

**Comment by NSoiffer** [comment]
Apologies that has taken me awhile to get to this. It is now fixed.

FYI: the problem equation has multiple lines inside the fraction. I suspect that isn't what you wanted. However, the bug you uncovered was a missing initialization in multi-line equations in general.
