### ISSUE TITLE
'&' not showing up in braille panel

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCATForPython#8]
In the braille panel, `Highlight with dots 7 &amp; 8 the current nav node` ends up displaying as `Highlight with dots 7  8 the current nav node`.

In the file that gets generated, there is just a `&` in place of the `&amp;` and that goes away in the display. If I change it to `&&` in the generated file, the `&` shows up. I'm not sure what it needs to be in the builder file.

**Comment by ways2read** [comment]
Fixed in #11
